apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpressdeployment
  labels:
    deploy: wordpress1 
spec:
  replicas: 2
  selector: 
    matchLabels:
      deploy: wordpress
  template:
    metadata:
      labels:
        deploy: wordpress
#spec for pods 
    spec:
      containers:
      - name: wordpress
        image: hebafarouk/wordpress22:latest
        ports:
          - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql_database:3306"
        - name: WORDPRESS_DB_USER
          value: "wp_user"
        - name: WORDPRESS_DB_PASSWORD
          value: "1234"
        - name: WORDPRESS_DB_NAME
          value: "wp_db"  
     