version: "3"
services:
 #database mysql layer 
  mysql_database:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
#  wordpress 
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:   
      - mysql_database
    image: wordpress:latest   
    restart: always
    ports:
      - 6666:80
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user           #the same as database it is user of wp that connect to db
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db             # name of db of wordpress
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}