name: Docker Image CI , k8s Deployment CD
on:
  push:
    branches: main

jobs:
# login to Docker Hub
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
               
      - name: checkout code 
        uses: actions/checkout@v4
     
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build --tag hebafarouk/wordpress2024:latest
      
      - name: Docker image push 
        run: docker push hebafarouk/wordpress2024:latest