name: Docker Image CI , k8s Deployment CD
on:
  push:
    branches: main
jobs:
# login to Docker Hub
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout code 
        uses: actions/checkout@v4
# build docker compose and create image
      - name: create image
        run: docker-compose -f Docker/docker-compose.yml build -t hebafarouk/wordpress2024:latest 
       
     # - name: Set image name
      #  run: sed -i 's|image:.*|image:hebafarouk/wordpress2024:latesttest|' Docker/docker-compose.yml   
          
#- name: Build Docker image
    #   run: docker-compose -f Docker/docker-compose.yml build -t hebafarouk/wordpress2024:latest 
      #- name: change name of image       
      - name: list docker images  
        run: docker image ls

      - name: list docker containers 
        run: docker container ls

        #push image on Docker Hub 
      - name: Docker image push 
        run: docker push hebafarouk/wordpress2024:latest
